version: '3.8'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "3001:3001"
      - "80:80"
    expose:
      - "3000"
      - "8000"
      - "80"
      # "HOST:CONTAINER"
      # "LOCAL:CONTAINER" acronym LOCO.
      # In the example above, Docker mapped the 8080 port inside of the container to the port 49160 on your machine.
    volumes:
      - ".:/usr/src/app"
    # What is links? (deleted for helm)
#    links:
#      - rabbitmq
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - 5672:5672
      - 15672:15672
      - 25672:25672

