# WARNING
# After installation, you must associate it with the Ingress rules
# kubectl patch ingress demo -p '{"metadata":{"annotations":{"konghq.com/plugins":"add-response-header"}}}'
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: add-response-header
config:
  add:
    headers:
      - "demo: injected-by-kong"
plugin: response-transformer
