# To test: curl -I $PROXY_IP/foo -H 'apikey: my-sooper-secret-key'
# Authentication must be set up first to use the above command
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: global-rate-limit
  labels:
    global: "true"
config:
  minute: 5
  limit_by: consumer
  policy: local
plugin: rate-limiting
