apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
spec:
  containers:
    - name: test-container
      image: nginx
      volumeMounts:
        # name must match the volume name below
        - name: secret-volume
          mountPath: /etc/secret-volume
  # The secret data is exposed to Containers in the Pod through a Volume.
  volumes:
    # name must match the volumeMounts name above
    - name: secret-volume
      secret:
        # This is the pod name given in set 2.1 or 2.shortcut
        # To see names `kubectl get secret`
        secretName: test-secret
