apiVersion: v1
kind: Pod
metadata:
  name: env-single-secret
spec:
  containers:
    - name: envars-test-container
      image: nginx
      env:
        # key name in container
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              # name of the 'secret' pod
              name: backend-user
              # key of the 'secret' inside the 'secret' pod
              key: backend-username
