version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - 5672:5672
      - 15672:15672
      - 25672:25672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
  node:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOSTNAMERABBIT=rabbitmq
    volumes:
      - ".:/usr/src/app"
    ports:
      - 80:80
    restart: on-failure
    depends_on:
      - rabbitmq
