apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: demo
#  DNS-CERTIFICATION
#  TO VERIFY:
# kubectl get secret dns.super-secret-service-account -n istio-system -o jsonpath="{.data['cert-chain\.pem']}" | base64 --decode | openssl x509 -in /dev/stdin -text -noout
  meshConfig:
    certificates:
      - secretName: dns.super-secret-service-account
        dnsNames: [ my-application.istio-system.svc, my-application.istio-system ]

