version: '3.8'

services:
  #############################################
  ############ setup node container ###########
  #############################################
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - "49160:8080"
        # In the example above, Docker mapped the 8080 port inside of the container to the port 49160 on your machine.
    volumes:
      - "./server:/usr/src/app"
  #############################################
  ############ setup client container ###########
  #############################################
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    expose:
     - "3000"
    ports:
      - "3000:3000"
      # "LOCAL:DOCKER"
      # "OUTSIDE:INSIDE"
      # In the example above, Docker mapped the 3000 (2) port inside of the container to the port 3000 (1) on your machine.
    volumes:
      - "./client/src:/app/client/src"
      - "./client/public:/app/client/public"
    links:
      - server
    stdin_open: true

