#SEE OUTPUT
#kubectl get cronjob <name>
#pods=$(kubectl get pods --selector=job-name=<full_name> --output=jsonpath={.items[*].metadata.name})
#kubectl logs $pods
#COULD IT BE THAT WITHOUT ISTIO I CANNOT ACCESS THE CONTAINER WITH CURL?
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-istio-disabled-2-b
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            # disable istio on the pod due to this issue:
            # https://github.com/istio/istio/issues/11659
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: hello-dev
              image: curlimages/curl
              # command is not executed within a shell. hence: 'sh'
              command: [
                  'sh',
                  '-c',
              ]
              # args executed within the context of the cluster
              # log the output https://stackoverflow.com/questions/5427454/how-do-i-pipe-or-redirect-the-output-of-curl-v
#              args: ["curl http://frontend:77; sleep 3600"]
#              args: ["curl http://frontend:77  &> /dev/stdout | tee; sleep 3600"]
              # RESPONSE TYPE:
#              args: ["output=$(curl -I http://frontend:77 | head -n 1| cut -d $' ' -f2); echo $output; sleep 3600"]
              args: ["output=$(curl http://frontend:77); echo $output; sleep 3600"]

          restartPolicy: OnFailure
