apiVersion: apps/v1
# Deployment => Scalable group of identical pods
kind: Deployment
metadata:
  name: bb-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
# Pod described under template
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
        - name: bb-site
          image: bulletinboard:1.0
---
apiVersion: v1
# NodePort Service => Route Traffic from port 30001 on the host
# to port 8080 inside the pods it routs to, allowing you to reach your
# bulletin board from the network.
kind: Service
metadata:
  name: bb-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
