apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: infura-cron-test
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              args:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
#                -
                # READING: https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/
                # Can I see the output?
                # CURL THE API END POINT..
          restartPolicy: OnFailure
