apiVersion: v1
kind: Service
metadata:
  name: hello-world-1
spec:
  ports:
  - port: 3000
  type: LoadBalancer
  selector:
    app: hello-world-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-1
spec:
  selector:
    matchLabels:
      app: hello-world-1
  template:
    metadata:
      labels:
        app: hello-world-1
    spec:
      containers:
      - name: hello-world-1
        image: node-phase-3-hello-world
        ports:
        - containerPort: 3000
